package varlink

import (
	"encoding/json"
	"strings"
)

// RegistryInterface holds metadata about a Varlink interface.
type RegistryInterface struct {
	Name       string
	Definition string
}

// Registry acts as a request dispatcher that routes Varlink calls to
// appropriate interface handlers based on the method namespace.
//
// It also implements the 'org.varlink.service' introspection methods.
type Registry struct {
	// interfaces holds a mapping between a Varlink namespace and
	// RegistryInterface. It is populated by the library users, by
	// calling the Register method.
	interfaces map[string]RegistryInterface
	handlers   map[string]Handler
	Vendor     string
	Product    string
	Version    string
	Url        string
}

func NewRegistry() *Registry {
	return &Registry{
		interfaces: make(map[string]RegistryInterface),
		handlers:   make(map[string]Handler),
	}
}

// Add registers a new namespace and handler with the registry. This
// gets called from autogenerated code inside the Register method.
func (r *Registry) Add(iface *RegistryInterface, handler Handler) {
	r.interfaces[iface.Name] = *iface
	r.handlers[iface.Name] = handler
}

// getInfoOut is returned by handleGetInfo, containing socket information.
type getInfoOut struct {
	Vendor     string   `json:"vendor"`
	Product    string   `json:"product"`
	Version    string   `json:"version"`
	URL        string   `json:"url"`
	Interfaces []string `json:"interfaces"`
}

// getInterfaceDescriptionIn is received during introspection.
type getInterfaceDescriptionIn struct {
	Interface string `json:"interface"`
}

// getInterfaceDescriptionOut is the introspection response,
// containing the string representation of the Varlink API.
type getInterfaceDescriptionOut struct {
	Description string `json:"description"`
}

// handleGetInfo implements 'org.varlink.service.GetInfo' method, returning
// getInfoOut with socket information, and a list of implemented interfaces.
func (r *Registry) handleGetInfo(call *ServerCall) error {
	interfaces := make([]string, 0, len(r.interfaces))
	for _, iface := range r.interfaces {
		interfaces = append(interfaces, iface.Name)
	}

	return call.CloseWithReply(getInfoOut{
		Product:    r.Product,
		Vendor:     r.Vendor,
		Version:    r.Version,
		URL:        r.Url,
		Interfaces: interfaces,
	})
}

// handleGetInterfaceDescription implements 'org.varlink.service.GetInterfaceDescription' method,
// returning getInterfaceDescriptionOut.
func (r *Registry) handleGetInterfaceDescription(call *ServerCall, req *ServerRequest) error {
	var in getInterfaceDescriptionIn
	if err := json.Unmarshal(req.Parameters, &in); err != nil {
		return &ServerError{
			Name:       "org.varlink.service.InvalidParameter",
			Parameters: map[string]string{"parameter": "interface"},
		}
	}

	iface, ok := r.interfaces[in.Interface]
	if !ok {
		return &ServerError{
			Name:       "org.varlink.service.InterfaceNotFound",
			Parameters: map[string]string{"interface": in.Interface},
		}
	}

	return call.CloseWithReply(getInterfaceDescriptionOut{
		Description: iface.Definition,
	})
}

// HandleVarlink dispatches calls to the appropriate interface handlers.
func (r *Registry) HandleVarlink(call *ServerCall, req *ServerRequest) error {
	switch req.Method {
	case "org.varlink.service.GetInfo":
		return r.handleGetInfo(call)
	case "org.varlink.service.GetInterfaceDescription":
		return r.handleGetInterfaceDescription(call, req)
	}

	lastDot := strings.LastIndexByte(req.Method, '.')
	if lastDot <= 0 {
		lastDot = 0
	}

	handler, ok := r.handlers[req.Method[:lastDot]]
	if !ok {
		return &ServerError{
			Name:       "org.varlink.service.InterfaceNotFound",
			Parameters: map[string]string{"interface": req.Method},
		}
	}

	return handler.HandleVarlink(call, req)
}
